# Generated by Django 6.1 on 2026-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_faculty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clearance_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
