# Generated by Django 6.1 on 2026-09-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLevel',
            fields=[
                ('level', models.PositiveIntegerField(help_text='0, 1, 2…', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Admin-defined name, e.g. Basic, Intermediate', max_length=64)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('equipment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('required_clearance', models.PositiveIntegerField(default=0, help_text='Minimum clearance level needed to auto-book this lab')),
                ('open_time', models.TimeField(default='09:00', help_text='Lab opens at this time')),
                ('close_time', models.TimeField(default='17:00', help_text='Lab closes at this time')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(choices=[(1, '1 hour'), (2, '2 hours')], default=1, help_text='Booking duration in hours')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('purpose', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='labs.laboratory')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('laboratory', 'date', 'start_time'), name='unique_approved_booking_per_slot')],
            },
        ),
    ]
