# Generated by Django 6.1 on 2026-09-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_seed_default_clearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='labs.laboratory'),
        ),
    ]
