# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_booking_laboratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_in_advance', models.PositiveIntegerField(
                    default=30,
                    help_text='Maximum number of days in advance a student can book a lab.',
                )),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
    ]
