# Generated by Django 6.1 on 2026-08-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='policy_documents/')),
                ('access_levels', models.JSONField(default=list, help_text='List of roles that can access this document. e.g. ["student", "faculty", "public"]')),
                ('effective_date', models.DateField(help_text='Date this policy takes effect')),
                ('is_ingested', models.BooleanField(default=False, help_text='Has this been vectorized in Qdrant?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
