# Generated by Django 6.1 on 2026-08-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_rag', '0004_enhanced_rag_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameIndex(
            model_name='documentchunkmetadata',
            new_name='knowledge_r_documen_1980ca_idx',
            old_name='knowledge_rag_chunk_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='institutionaldocument',
            new_name='knowledge_r_categor_957aa9_idx',
            old_name='knowledge_rag_category_idx',
        ),
        migrations.RenameIndex(
            model_name='institutionaldocument',
            new_name='knowledge_r_is_inge_9ccbd8_idx',
            old_name='knowledge_rag_ingested_idx',
        ),
        migrations.RenameIndex(
            model_name='institutionaldocument',
            new_name='knowledge_r_effecti_cc4c0e_idx',
            old_name='knowledge_rag_effdate_idx',
        ),
    ]
