# Generated by Django 6.1 on 2026-08-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(default='academic_question', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Human Approval'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='OPEN', max_length=20),
        ),
    ]
