# Generated by Django 6.1 on 2026-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_servicerequest_category_servicerequest_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='agent_thread_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
