# Generated by Django 6.1 on 2026-08-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('step_number', models.IntegerField()),
                ('retrieved_docs', models.JSONField(default=list, help_text='RAG chunks used for context')),
                ('action_taken', models.CharField(max_length=255)),
                ('executed_by_human', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.servicerequest')),
            ],
        ),
    ]
